workload:
  model: moonshotai/Kimi-K3
  modelPath: /data/model/huggingface_model_cache/models--moonshotai--Kimi-K3
  image: lmsysorg/sglang:kimi-k3
  framework: sglang
  nnodes: 4
  tpSize: 16
  trustRemoteCode: true
  reasoningParser: kimi_k3
  toolCallParser: kimi_k3
  mambaFullMemoryRatio: 0.86
  memFractionStatic: 0.85
  extraPipPackages: hf_transfer fla-core
  serviceAccountName: workload-identity-k8s-sa

volumes:
  gcsfuse:
    bucketName: <YOUR_GCS_BUCKET>
