run:
  name: llama3_70b_64gpus_tp2_pp4_cp1_vp5_gbs128_mbs1_fp8
  results_dir: ${base_results_dir}/${.name}
  time_limit: "0-02:30:00"
  dependency: "singleton"
trainer:
  devices: 8
  accelerator: gpu
  precision: bf16
  logger: false # logger provided by exp_manager
  enable_checkpointing: false
  use_distributed_sampler: false
  max_epochs: null
  max_steps: 20 # consumed_samples = global_step * global_batch_size
  max_time: "05:23:30:00" # days:hours:minutes:seconds
  log_every_n_steps: 1
  val_check_interval: null
  limit_val_batches: 0.0
  limit_test_batches: 5
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
exp_manager:
  exp_dir: null
  name: megatron_llama
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: nemo_llama_pretrain
    name: ${run.name}
  create_dllogger_logger: True
  dllogger_logger_kwargs:
    verbose: True
    stdout: True
    json_file: "./dllogger.json"     
  resume_if_exists: false
  resume_ignore_no_checkpoint: true
  create_checkpoint_callback: false
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 10
    mode: min
    always_save_nemo: False # saves nemo file during validation, not implemented for model parallel
    save_nemo_on_train_end: False # not recommended when training large models on clusters with short time limits
    filename: 'megatron_llama--{val_loss:.2f}-{step}-{consumed_samples}'
    model_parallel_size: ${multiply:${model.tensor_model_parallel_size}, ${model.pipeline_model_parallel_size}}
  log_step_timing: true
  step_timing_kwargs:
    sync_cuda: true
    buffer_size: 5
  seconds_to_sleep: 60
model:
  tp_only_amax_red: true
  mcore_gpt: true
  micro_batch_size: 1
  global_batch_size: 128
  rampup_batch_size: null
  tensor_model_parallel_size: 2
  pipeline_model_parallel_size: 4
  virtual_pipeline_model_parallel_size: 5
  context_parallel_size: 1
  encoder_seq_length: 8192
  max_position_embeddings: 8192
  num_layers: 80
  hidden_size: 8192
  ffn_hidden_size: 28672
  num_attention_heads: 64
  num_query_groups: 8
  init_method_std: 0.00894
  use_scaled_init_method: true
  hidden_dropout: 0.0
  attention_dropout: 0.0
  ffn_dropout: 0.0
  kv_channels: null
  apply_query_key_layer_scaling: true
  normalization: rmsnorm
  layernorm_epsilon: 1.0e-05
  do_layer_norm_weight_decay: false
  make_vocab_size_divisible_by: 128
  pre_process: true
  post_process: true
  persist_layer_norm: true
  bias: false
  activation: fast-swiglu
  headscale: false
  transformer_block_type: pre_ln
  openai_gelu: false
  normalize_attention_scores: true
  position_embedding_type: rope
  rotary_percentage: 1.0
  apply_rope_fusion: true
  attention_type: multihead
  share_embeddings_and_output_weights: false
  scale_positional_embedding: true
  tokenizer:
    library: 'megatron'
    type: 'GPT2BPETokenizer'
    model: null
    delimiter: null  # only used for tabular tokenizer
    vocab_file: gpt2-vocab.json
    merge_file: gpt2-merges.txt     
  native_amp_init_scale: 4294967296
  native_amp_growth_interval: 1000
  hysteresis: 2
  fp32_residual_connection: false
  fp16_lm_cross_entropy: false
  megatron_amp_O2: true
  grad_allreduce_chunk_size_mb: 125
  grad_div_ar_fusion: true
  gradient_accumulation_fusion: true
  cross_entropy_loss_fusion: true
  bias_activation_fusion: true
  bias_dropout_add_fusion: true
  masked_softmax_fusion: true
  seed: 1234
  resume_from_checkpoint: null
  use_cpu_initialization: false
  onnx_safe: false
  apex_transformer_log_level: 30
  gradient_as_bucket_view: true
  sync_batch_comm: false
  activations_checkpoint_granularity: null
  activations_checkpoint_method: null
  activations_checkpoint_num_layers: null
  num_micro_batches_with_partial_activation_checkpoints: null
  activations_checkpoint_layers_per_pipeline: null
  sequence_parallel: true
  defer_embedding_wgrad_compute: true
  wgrad_deferral_limit: 50
  deterministic_mode: false

  ## Transformer Engine
  transformer_engine: true
  fp8: true # enables fp8 in TransformerLayer forward  
  fp8_e4m3: False # sets fp8_format = recipe.Format.E4M3
  fp8_hybrid: true # sets fp8_format = recipe.Format.HYBRID
  fp8_margin: 0 # scaling margin
  fp8_interval: 1 # scaling update interval
  fp8_amax_history_len: 1024 # Number of steps for which amax history is recorded per tensor
  fp8_amax_compute_algo: max # 'most_recent' or 'max'. Algorithm for computing amax from history
  fp8_params: true
  ub_tp_comm_overlap: true
  ub_tp_comm_overlap_cfg:
# # B200 bf16
#     fc1_dgrad:
#       cga_size: 2
#       method: bulk
#       num_sm: 2
#       set_sm_margin: 0
#     fc1_fprop:
#       aggregate: 0
#       method: ring_exchange
#       num_sm: 1
#       set_sm_margin: 0
#     fc1_wgrad:
#       cga_size: 2
#       method: bulk
#       num_sm: 8
#       set_sm_margin: 0
#     fc2_dgrad:
#       aggregate: 0
#       method: ring_exchange
#       num_sm: 1
#       set_sm_margin: 0
#     fc2_fprop:
#       aggregate: 1
#       method: ring_exchange
#       num_sm: 1
#       set_sm_margin: 1
#     proj_dgrad:
#       aggregate: 0
#       method: ring_exchange
#       num_sm: 1
#       set_sm_margin: 0
#     proj_fprop:
#       aggregate: 1
#       method: ring_exchange
#       num_sm: 1
#       set_sm_margin: 1
#     qkv_dgrad:
#       cga_size: 2
#       method: bulk
#       num_sm: 8
#       set_sm_margin: 0
#     qkv_fprop:
#       aggregate: 0
#       method: ring_exchange
#       num_sm: 1
#       set_sm_margin: 0
#     qkv_wgrad:
#       cga_size: 2
#       method: bulk
#       num_sm: 32
#       set_sm_margin: 0
  
# B200 fp8
    fc1_dgrad:
      cga_size: 2
      method: bulk
      num_sm: 2
      set_sm_margin: 0
    fc1_fprop:
      aggregate: 0
      method: ring_exchange
      num_sm: 1
      set_sm_margin: 0
    fc1_wgrad:
      cga_size: 2
      method: bulk
      num_sm: 4
      set_sm_margin: 0
    fc2_dgrad:
      aggregate: 0
      method: ring_exchange
      num_sm: 1
      set_sm_margin: 0
    fc2_fprop:
      aggregate: 1
      method: ring_exchange
      num_sm: 1
      set_sm_margin: 1
    proj_dgrad:
      aggregate: 0
      method: ring_exchange
      num_sm: 1
      set_sm_margin: 0
    proj_fprop:
      aggregate: 1
      method: ring_exchange
      num_sm: 1
      set_sm_margin: 1
    qkv_dgrad:
      cga_size: 2
      method: bulk
      num_sm: 4
      set_sm_margin: 0
    qkv_fprop:
      aggregate: 0
      method: ring_exchange
      num_sm: 1
      set_sm_margin: 0
    qkv_wgrad:
      cga_size: 2
      method: bulk
      num_sm: 24
      set_sm_margin: 0

  use_flash_attention: true
  overlap_p2p_comm: true
  batch_p2p_comm: false
  gc_interval: 100
  nsys_profile:
    enabled: false
    trace: [nvtx,cuda]
    start_step: 25  # Global batch to start profiling
    end_step: 30 # Global batch to end profiling
    ranks: [0] 
    gen_shape: False # Generate model and kernel details including input shapes
  optim:
    name: distributed_fused_adam
    # name: mcore_distributed_optim
    lr: 0.00015
    weight_decay: 0.1
    betas:
    - 0.9
    - 0.95
    bucket_cap_mb: 125
    overlap_grad_sync: true
    overlap_param_sync: true
    contiguous_grad_buffer: true
    contiguous_param_buffer: true
    grad_sync_dtype: bf16
    sched:
      name: CosineAnnealing
      warmup_steps: 2000
      constant_steps: 11873
      min_lr: 1.0e-05
  data:
    # data_impl: mmap
    data_impl: mock
    splits_string: 99990,8,2
    seq_length: 8192
    skip_warmup: true
    num_workers: 2
    dataloader_type: single
    reset_position_ids: false
    reset_attention_mask: false
    eod_mask_loss: false
    index_mapping_dir: null