apiVersion: resource.nvidia.com/v1beta1
kind: ComputeDomain
metadata:
  name: {{ .Release.Name }}-compute-domain
  namespace: {{ .Release.Namespace }}
spec:
  numNodes: {{ .Values.workload.nnodes | default 4 }}
  channel:
    resourceClaimTemplate:
      name: {{ .Release.Name }}-compute-domain-claim
