apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 30100
      targetPort: 30100
      protocol: TCP
  selector:
    leaderworkerset.sigs.k8s.io/name: {{ .Release.Name }}
    leaderworkerset.sigs.k8s.io/worker-index: "0"
