apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-launcher"
data:
  launch-workload.sh: |-
{{- if .Values.workload_launcher }}
{{ .Values.workload_launcher | nindent 4 }}
{{- else }}
    #!/bin/bash
    echo "No workload launcher specified"
    exit 1
{{- end }}
