# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

run:
  name: gpt3_175b
  results_dir:
  time_limit: 26-00:00:00
  dependency: singleton
trainer:
  devices: 8
  accelerator: gpu
  precision: bf16
  logger: false
  enable_checkpointing: false
  use_distributed_sampler: false
  max_epochs: null
  max_steps: 50
  max_time: '25:23:00:00'
  log_every_n_steps: 1
  val_check_interval: 100
  limit_val_batches: 20
  limit_test_batches: 20
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
exp_manager:
  exp_dir:
  name: megatron_gpt
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: nemo_gpt3
    name: ${run.name}
  create_dllogger_logger: true
  dllogger_logger_kwargs:
    verbose: true
    stdout: true
  resume_if_exists: false
  resume_ignore_no_checkpoint: true
  create_checkpoint_callback: false
  checkpoint_callback_params:
    monitor: val_loss
    save_top_k: 5
    mode: min
    always_save_nemo: false
    save_nemo_on_train_end: false
    filename: megatron_gpt--{val_loss:.2f}-{step}-{consumed_samples}
    model_parallel_size: ${multiply:${model.tensor_model_parallel_size}, ${model.pipeline_model_parallel_size}}
  log_step_timing: true
  step_timing_kwargs:
    sync_cuda: true
    buffer_size: 5
  explicit_log_dir:
model:
  micro_batch_size: 1
  global_batch_size: 2048
  context_parallel_size: 1
  tensor_model_parallel_size: 4
  pipeline_model_parallel_size: 8
  virtual_pipeline_model_parallel_size: 2
  resume_from_checkpoint: null
  encoder_seq_length: 2048
  max_position_embeddings: 2048
  num_layers: 96
  hidden_size: 12288
  ffn_hidden_size: ${multiply:4, ${.hidden_size}}
  num_attention_heads: 96
  init_method_std: 0.006
  hidden_dropout: 0.1
  attention_dropout: 0.1
  kv_channels: null
  apply_query_key_layer_scaling: true
  layernorm_epsilon: 1.0e-05
  make_vocab_size_divisible_by: 128
  pre_process: true
  post_process: true
  persist_layer_norm: true
  gradient_as_bucket_view: true
  grad_div_ar_fusion: true
  gradient_accumulation_fusion: true
  bias_activation_fusion: true
  bias_dropout_add_fusion: true
  masked_softmax_fusion: true
  fsdp: false
  fsdp_sharding_strategy: full
  fsdp_grad_reduce_dtype: 32
  fsdp_sharded_checkpoint: false
  activations_checkpoint_granularity: null
  activations_checkpoint_method: null
  activations_checkpoint_num_layers: null
  num_micro_batches_with_partial_activation_checkpoints: null
  activations_checkpoint_layers_per_pipeline: null
  sequence_parallel: true
  num_query_groups: null
  tokenizer:
    library: megatron
    type: GPT2BPETokenizer
    model: null
    delimiter: null
    vocab_file: gpt2-vocab.json
    merge_file: gpt2-merges.txt
  native_amp_init_scale: 4294967296
  native_amp_growth_interval: 1000
  hysteresis: 2
  fp32_residual_connection: false
  fp16_lm_cross_entropy: false
  megatron_amp_O2: true
  grad_allreduce_chunk_size_mb: 125
  sharp: false
  mcore_gpt: true
  transformer_engine: true
  fp8: true
  fp8_e4m3: false
  fp8_hybrid: true
  fp8_margin: 0
  fp8_interval: 1
  fp8_amax_history_len: 1024
  fp8_amax_compute_algo: max
  fp8_wgrad: true
  ub_tp_comm_overlap: false
  tp_comm_atomic_ag: false
  tp_comm_atomic_rs: false
  seed: 1234
  sync_batch_comm: false
  use_cpu_initialization: false
  onnx_safe: false
  apex_transformer_log_level: 30
  overlap_p2p_comm: true
  batch_p2p_comm: false
  nsys_profile:
    enabled: false
    trace:
    - nvtx
    - cuda
    start_step: 41
    end_step: 43
    ranks:
    - 0
    gen_shape: false
  optim:
    name: distributed_fused_adam
    bucket_cap_mb: 220
    overlap_grad_sync: true
    overlap_param_sync: true
    contiguous_grad_buffer: true
    grad_sync_dtype: bf16
    lr: 9.0e-05
    weight_decay: 0.1
    betas:
    - 0.9
    - 0.95
    sched:
      name: CosineAnnealing
      warmup_steps: 115
      constant_steps: 12500
      min_lr: 9.0e-06
  data:
    data_impl: mock
    splits_string: 90,8,2
    seq_length: 2048
    skip_warmup: true
    num_workers: 2
    exchange_indices_distributed: true
    dataloader_type: single
    reset_position_ids: false
    reset_attention_mask: false
    eod_mask_loss: false
    index_mapping_dir: null
    data_prefix: []
