dwsSettings:
  maxRunDurationSeconds: null
network:
  gibVersion: us-docker.pkg.dev/gce-ai-infra/gpudirect-gib/nccl-plugin-gib:v1.1.0
  hostNetwork: true
  ncclSettings:
  - name: NCCL_DEBUG
    value: WARN
  subnetworks[]: null
queue: null
tasSettings:
  topologyRequest:
    kueue.x-k8s.io/podset-preferred-topology: kubernetes.io/hostname
volumes:
  gcsMounts:
  - bucketName: null
    mountPath: null
  gcsVolumes: true
  psVolumes: false
workload:
  arguments[]: null
  configFile: main.py
  configPath: /workload/configs/
  defaultArguments[]: null
  envs:
  - name: ARTIFACT_DIR
    value: null
  - name: GLOO_SOCKET_IFNAME
    value: eth0
  - name: PYTHON_MAIN
    value: /workload/configs/main.py
  gpus: 32
  image: nvcr.io/nvidia/pytorch:25.01-py3
