# yamllint disable
{{- if .Values.is_multi_host }}
{{- fail "Multi-host for GPU is not supported in this template." }}
{{- end }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ .Release.Name }}-hyperdisk-balanced"
provisioner: pd.csi.storage.gke.io
parameters:
  type: hyperdisk-balanced
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-hd-claim"
spec:
  storageClassName: "{{ .Release.Name }}-hyperdisk-balanced"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.server.data_disk_size}}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-hf-secret"
type: Opaque
stringData:
  hf_api_token: {{.Values.hf_token}}
---
{{- if .Values.gcp_service_account }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.k8s_service_account | quote }}
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp_service_account }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-gpu-server"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-gpu-pod"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-gpu-pod"
        {{- if .Values.kueue_local_queue }}
        kueue.x-k8s.io/queue-name: {{ .Values.kueue_local_queue | quote }}
        {{- end }}
    spec:
      {{- if .Values.gcp_service_account }}
      serviceAccountName: {{ .Values.k8s_service_account | quote }}
      {{- end }}
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-b200
      tolerations:
      - operator: "Exists"
        key: nvidia.com/gpu
      - operator: "Exists"
        key: cloud.google.com/impending-node-termination
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
      containers:
      - name: vllm-gpu
        image: {{.Values.server.image}}
        command: ["/bin/bash", "-c"]
        args:
        - {{ .Values.server.bash_command | quote }}
        env:
        - name: LD_LIBRARY_PATH
          value: /usr/local/gib/lib64:/usr/local/nvidia/lib64
        - name: NCCL_DEBUG
          value: INFO
        - name: NCCL_IGNORE_DISABLED_P2P
          value: "1"
        - name: HF_HOME
          value: /data
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-hf-secret"
              key: hf_api_token
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: "{{.Values.server.num_chips_per_node}}"
          requests:
            nvidia.com/gpu: "{{.Values.server.num_chips_per_node}}"
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - mountPath: "/data"
          name: data-volume
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: data-volume
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-hd-claim"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-vllm-service"
spec:
  selector:
    app: "{{ .Release.Name }}-gpu-pod"
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-client"
  labels:
    {{- if .Values.kueue_local_queue }}
    kueue.x-k8s.io/queue-name: {{ .Values.kueue_local_queue | quote }}
    {{- end }}
spec:
  {{- if .Values.gcp_service_account }}
  serviceAccountName: {{ .Values.k8s_service_account | quote }}
  {{- end }}
  tolerations:
  - operator: "Exists"
    key: nvidia.com/gpu
  - operator: "Exists"
    key: cloud.google.com/impending-node-termination
  terminationGracePeriodSeconds: 60
  containers:
  - name: vllm-bench
    image: {{.Values.client.image}}
    command: ["/bin/bash", "-c"]
    args: ["{{.Values.client.bash_command}}"]
    env:
    - name: HUGGING_FACE_HUB_TOKEN
      valueFrom:
        secretKeyRef:
          key: hf_api_token
          name: "{{ .Release.Name }}-hf-secret"
    - name: SERVER_HOSTNAME
      value: "{{ .Release.Name }}-vllm-service.default.svc.cluster.local"
  restartPolicy: Never
