queue: null
dwsSettings:
  maxRunDurationSeconds: null
tasSettings:
  topologyRequest:
    kueue.x-k8s.io/podset-preferred-topology: kubernetes.io/hostname
volumes:
  gcsVolumes: true
  psVolumes: false
  gcsMounts:
    - bucketName: null
      mountPath: null
workload:
  gpus: 256
  image: nvcr.io/nvidia/nemo:25.11
  defaultArguments[]: null
  arguments[]: null
  configFile: llama3-1-70b-bf16-seq8192-gbs256-gpus256.py
  configPath: /workload/configs/
  envs:
    - name: ARTIFACT_DIR
      value: null
    - name: GLOO_SOCKET_IFNAME
      value: eth0
    - name: NEMO_LAUNCH_SCRIPT
      value: /workload/configs/llama3-1-70b-bf16-seq8192-gbs256-gpus256.py
network:
  hostNetwork: true
  subnetworks[]: null
  gibVersion: us-docker.pkg.dev/gce-ai-infra/gpudirect-gib/nccl-plugin-gib:v1.1.1
  ncclSettings:
    - name: NCCL_DEBUG
      value: WARN
