# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{$timestamp := now | date "2006-01-02-15-04-05"}}
{{$jobSuffix := randAlphaNum 4 | lower}}
{{$jobuuid := uuidv4}}
{{$nodes := div .Values.workload.gpus 4 | max 1}}
{{$gpusPerNode := min .Values.workload.gpus 4}}
{{- $root := . -}}
apiVersion: resource.nvidia.com/v1beta1
kind: ComputeDomain
metadata:
  name: "{{ .Release.Name }}-{{ $jobSuffix }}"
spec:
  numNodes: {{ $nodes }}
  channel:
    resourceClaimTemplate:
      name: "{{ .Release.Name }}-{{ $jobSuffix }}-channel"
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: "{{ .Release.Name }}-{{ $jobSuffix }}-all-mrdma"
spec:
  spec:
    devices:
      requests:
      - name: req-mrdma
        exactly:
          deviceClassName: mrdma.google.com
          allocationMode: ExactCount
          count: 8
---
apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: "{{ .Release.Name }}"
  namespace: default
  labels:
  {{- if $root.Values.queue }}
    kueue.x-k8s.io/queue-name: "{{ $root.Values.queue }}"
  {{- end }}
spec:
  {{- if $root.Values.queue }}
  suspend: true
  {{- end }}
  failurePolicy:
    maxRestarts: {{ default 0 $root.Values.workload.max_workload_restarts }}
  replicatedJobs:
  - name: workload
    replicas: 1
    template:
      spec:
        parallelism: {{ $nodes }}
        completions: {{ $nodes }}
        backoffLimit: 0
        completionMode: Indexed
        activeDeadlineSeconds: 14400 # 4 hours (4 * 60 * 60)
        ttlSecondsAfterFinished: 43200 # 12 hours (12 * 60 * 60)
        template:
          metadata:
            annotations:
              kubectl.kubernetes.io/default-container: workload
              {{- if $root.Values.volumes.gcsVolumes }}
              gke-gcsfuse/volumes: "true"
              gke-gcsfuse/cpu-limit: "0"
              gke-gcsfuse/memory-limit: "0"
              gke-gcsfuse/ephemeral-storage-limit: "0"
              {{- end }}
              {{- if $root.Values.volumes.psVolumes }}
              gke-parallelstore/volumes: "true"
              gke-parallelstore/cpu-limit: "0"
              gke-parallelstore/memory-limit: "0"
              {{- end }}
              {{- if and $root.Values.queue $root.Values.tasSettings.topologyRequest }}
              {{- toYaml .Values.tasSettings.topologyRequest | nindent 14 }}
              {{- end }}
              {{- if and $root.Values.queue $root.Values.dwsSettings.maxRunDurationSeconds }}
              provreq.kueue.x-k8s.io/maxRunDurationSeconds: "{{ $root.Values.dwsSettings.maxRunDurationSeconds }}"
              {{- end }}

          spec:
            hostNetwork: {{ .Values.network.hostNetwork }}
            hostIPC: {{ .Values.network.hostIPC }}

            subdomain: "{{.Release.Name}}"
            restartPolicy: Never
            affinity:

              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: kubernetes.io/arch
                      operator: In
                      values:
                      - arm64
                    {{- if $root.Values.targetNodepools }}
                    - key: cloud.google.com/gke-nodepool
                      operator: In
                      values:
                      {{- range $nodepool := $root.Values.targetNodepools }}
                      - {{ $nodepool }}
                      {{- end }}
                    {{- end }}


            tolerations:
            - operator: "Exists"
              key: nvidia.com/gpu
            - operator: "Exists"
              key: cloud.google.com/impending-node-termination
            - key: "kubernetes.io/arch"
              operator: "Equal"
              value: "arm64"
              effect: "NoSchedule"

            volumes:
            - name: library-dir-host
              hostPath:
                path: /home/kubernetes/bin/nvidia


            {{- if $root.Values.workload.configFile }}
            - name: workload-configuration
              configMap:
                name: "{{.Release.Name}}-config"
                items:
                - key: workload-configuration
                  path: {{ $root.Values.workload.configFile | default "workload-configuration" }}
            {{- end }}

            - name: workload-launcher
              configMap:
                name: "{{.Release.Name}}-launcher"

            - name: shared-memory
              emptyDir:
                medium: "Memory"
                sizeLimit: 250Gi

            {{- range $pvc := $root.Values.volumes.pvcMounts }}
            - name: "{{ $pvc.claimName }}"
              persistentVolumeClaim:
                claimName: "{{ $pvc.claimName }}"
            {{- end }}

            {{- if $root.Values.volumes.gcsVolumes }}
            {{- range $gcs := $root.Values.volumes.gcsMounts }}
            - name: "{{ $gcs.bucketName }}"
              csi:
                driver: gcsfuse.csi.storage.gke.io
                volumeAttributes:
                  bucketName: "{{ $gcs.bucketName }}"
                  {{- if $gcs.mountOptions }}
                  mountOptions: "{{ $gcs.mountOptions }}"
                  {{- end }}
            {{- end}}
            {{- else }}
            {{- range $gcs := $root.Values.volumes.gcsMounts }}
            - name: "{{ $gcs.bucketName }}"
              emptyDir: {}
            {{- end }}
            {{- end }}

            {{- if $root.Values.volumes.ssdMountPath }}
            - name: local-ssd
              hostPath:
                path: /mnt/stateful_partition/kube-ephemeral-ssd
            {{- end }}



            resourceClaims:
            - name: compute-domain-channel
              resourceClaimTemplateName: "{{ .Release.Name }}-{{ $jobSuffix }}-channel"
            - name: rdma
              resourceClaimTemplateName: "{{ .Release.Name }}-{{ $jobSuffix }}-all-mrdma"

            containers:
            {{- if $root.Values.workload.gcsSidecarImage }}
            - name: gke-gcsfuse-sidecar
              image: {{ $root.Values.workload.gcsSidecarImage }}
            - name: gke-gcsfuse-metadata-prefetch
              image: {{ $root.Values.workload.gcsSidecarImage }}
            {{- end }}
            {{- if $root.Values.workload.psSidecarImage }}
            - name: gke-parallelstore-sidecar
              image: {{ $root.Values.workload.psSidecarImage }}
            {{- end }}

            - name: workload
              image: "{{ $root.Values.workload.image }}"
              imagePullPolicy: Always
              resources:
                requests:
                  nvidia.com/gpu: 4
                limits:
                  nvidia.com/gpu: 4
                claims:
                - name: compute-domain-channel
                - name: rdma
              securityContext:
                privileged: true
                capabilities:
                  add: ["IPC_LOCK"]
              env:
              - name: JOB_IDENTIFIER
                value: "{{ .Release.Name }}-{{ $timestamp }}"
              - name: JOB_TIMESTAMP
                value: "{{ $timestamp }}"
              - name: JOB_UUID
                value: "{{ $jobuuid }}"
              - name: JOB_ORCHESTRATOR
                value: "gke"
              # Add RANK based on the pod's index provided by the Indexed Job
              # This is crucial for torch.distributed initialization.
              - name: JOB_COMPLETION_INDEX
                valueFrom:
                  fieldRef:

                    fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
              - name: RANK_0_FQDN
                value: "{{.Release.Name}}-workload-0-0.{{.Release.Name}}.default.svc.cluster.local"
              - name: HOSTNAME_PREFIX
                value: "{{.Release.Name}}-workload-"
              - name: DOMAIN_NAME
                value: "{{.Release.Name}}.default.svc.cluster.local"
              - name: MASTER_ADDR
                value: "{{.Release.Name}}-workload-0-0.{{.Release.Name}}.default.svc.cluster.local"
              - name: MASTER_PORT
                value: "6002"
              - name: WORLD_SIZE
                value: "{{ $root.Values.workload.gpus }}"
              - name: NNODES
                value: "{{ $nodes }}"
              - name: GPUS_PER_NODE
                value: "{{ $gpusPerNode }}"
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName

              - name: LD_LIBRARY_PATH
                value: /usr/local/nvidia/lib64

              {{ if $root.Values.network.ncclSettings }}
              {{- toYaml .Values.network.ncclSettings | nindent 14 }}
              {{ end }}

              {{ if $root.Values.workload.envs }}
              {{- toYaml .Values.workload.envs | nindent 14 }}
              {{ end }}

              command:
              - bash
              - -c
              - |
                echo "Pod on $(hostname --fqdn) is running"
                echo "Pod is assigned job index of $JOB_COMPLETION_INDEX"
                echo "Pod is using node $NODE_NAME"

                # Install DOCA-OFED
                apt update -y
                apt install -y curl
                export DOCA_URL="https://linux.mellanox.com/public/repo/doca/3.1.0/ubuntu22.04/arm64-sbsa/"
                BASE_URL=$([ "${DOCA_PREPUBLISH:-false}" = "true" ] && echo https://doca-repo-prod.nvidia.com/public/repo/doca || echo https://linux.mellanox.com/public/repo/doca)
                DOCA_SUFFIX=${DOCA_URL#*public/repo/doca/}; DOCA_URL="$BASE_URL/$DOCA_SUFFIX"
                curl $BASE_URL/GPG-KEY-Mellanox.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/GPG-KEY-Mellanox.pub
                echo "deb [signed-by=/etc/apt/trusted.gpg.d/GPG-KEY-Mellanox.pub] $DOCA_URL ./" > /etc/apt/sources.list.d/doca.list
                apt update
                apt install -y --allow-downgrades --allow-change-held-packages -o Dpkg::Options::="--force-overwrite" doca-ofed-userspace

                # Install NCCL and nccl-gib-plugins package
                apt install --only-upgrade --allow-change-held-packages -y libnccl2 libnccl-dev

                # If image not from Google, trust the GCP signing key
                curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/cloud.google.gpg

                # Add gpudirect-gib-apt repo
                echo 'deb https://packages.cloud.google.com/apt gpudirect-gib-apt main' | tee /etc/apt/sources.list.d/nccl-gib.list

                apt update
                apt install nccl-gib-plugins

                rm -rf /opt/rdma-core/build/lib/libibverbs* || true
                export LD_LIBRARY_PATH="/usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu/libibverbs:/usr/lib/libibverbs:/usr/local/nccl-plugin/lib64:/usr/local/nvidia/lib64/:${LD_LIBRARY_PATH}"

                echo "Launching workload with the following arguments:"
                {{- range $root.Values.workload.defaultArguments }}
                echo "  {{ . }}"
                {{- end }}
                {{- range $root.Values.workload.arguments }}
                echo "  {{ . }}"
                {{- end }}
                echo ""

                sleep 10

                # # Stream dmesg logs to stdout.
                # dmesg -W &
                # DMESG_PID=$!
                # trap "kill -9 $DMESG_PID" EXIT

                bash /workload/launcher/launch-workload.sh \
{{- range $root.Values.workload.defaultArguments }}
                {{ . }} \
                {{- end }}
                {{- range $root.Values.workload.arguments }}
                {{ . }} \
                {{- end }}



              volumeMounts:
                - name: library-dir-host
                  mountPath: /usr/local/nvidia


                {{- if $root.Values.workload.configFile }}
                - name: workload-configuration
                  mountPath: {{ $root.Values.workload.configPath | default "/workload/configs" }}
                {{- end }}

                - name: workload-launcher
                  mountPath: /workload/launcher

                - name: shared-memory
                  mountPath: /dev/shm

                {{- range $pvc := $root.Values.volumes.pvcMounts }}
                - name: "{{ $pvc.claimName }}"
                  mountPath: "{{ $pvc.mountPath }}"
                {{- end }}

                {{- range $gcs := $root.Values.volumes.gcsMounts }}
                - name: "{{ $gcs.bucketName }}"
                  mountPath: "{{ $gcs.mountPath }}"
                {{- end }}

                {{- if $root.Values.volumes.ssdMountPath }}
                - name: local-ssd
                  mountPath: "{{ $root.Values.volumes.ssdMountPath }}"
                {{- end }}
