queue: null
dwsSettings:
  maxRunDurationSeconds: null
tasSettings:
  topologyRequest:
    kueue.x-k8s.io/podset-required-topology: cloud.google.com/gce-topology-block
    kueue.x-k8s.io/podset-slice-required-topology: cloud.google.com/gce-topology-subblock
    kueue.x-k8s.io/podset-slice-size: '16'
volumes:
  gcsVolumes: false
  psVolumes: false
  gcsMounts:
    - bucketName: null
      mountPath: null
workload:
  gpus: 256
  image: nvcr.io/nvidia/nemo:26.02
  hfToken: null
  defaultArguments[]: null
  arguments[]: null
  configFile: custom_setup_experiment.py
  configPath: /workload/configs/
  envs:
    - name: ARTIFACT_DIR
      value: null
    - name: GLOO_SOCKET_IFNAME
      value: eth0
    - name: CUSTOM_SETUP_EXPERIMENT_SCRIPT_PATH
      value: /workload/configs/custom_setup_experiment.py
network:
  hostNetwork: false
  hostIPC: true
  subnetworks[]: null
  ncclSettings:
    - name: NCCL_DEBUG
      value: WARN
